// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtiboO1nMOn2D2WSEUDOLm328xzdJWrrQ',
    appId: '1:737969088046:web:32e84ed0dd8f9a52fae1bf',
    messagingSenderId: '737969088046',
    projectId: 'nearo-8d5f0',
    authDomain: 'nearo-8d5f0.firebaseapp.com',
    storageBucket: 'nearo-8d5f0.appspot.com',
    measurementId: 'G-P0XT67HQ61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLyb8rhP3BipApgVr33LtIi2s0NxIObo',
    appId: '1:737969088046:android:f6860f81d7099bcefae1bf',
    messagingSenderId: '737969088046',
    projectId: 'nearo-8d5f0',
    storageBucket: 'nearo-8d5f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo3YALhF_uVGfVcn1iidMrcbEYB3Ue9bE',
    appId: '1:737969088046:ios:e7b68a6dea3b952efae1bf',
    messagingSenderId: '737969088046',
    projectId: 'nearo-8d5f0',
    storageBucket: 'nearo-8d5f0.appspot.com',
    iosClientId: '737969088046-npo2ieo4d8pcdc2kohnfpb4ikbslam7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbybluetooth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo3YALhF_uVGfVcn1iidMrcbEYB3Ue9bE',
    appId: '1:737969088046:ios:e7b68a6dea3b952efae1bf',
    messagingSenderId: '737969088046',
    projectId: 'nearo-8d5f0',
    storageBucket: 'nearo-8d5f0.appspot.com',
    iosClientId: '737969088046-npo2ieo4d8pcdc2kohnfpb4ikbslam7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbybluetooth',
  );
}
